[allowlist]
  description = "Allowlist"
  paths = [
    '''ignore\.d''',
    '''\.ignore\.txt$''',
    '''^\.?gitleaks.toml$''',
    '''^\.?export.sh$''',
    '''^\.?standalone/export.sh$''',
    '''^\.?standalone\/export.sh$''',
    '''^\.?cinder_v1beta1_cinder.yaml$''',
    '''^\.?crc/cr/cinder_v1beta1_cinder.yaml$''',
    '''^\.?crc/cr\/cinder_v1beta1_cinder.yaml$''',
    '''^\.?crc\/cr/cinder_v1beta1_cinder.yaml$''',
    '''^\.?crc\/cr\/cinder_v1beta1_cinder.yaml$''',
  ]
