---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: network-edpm-compute-0
spec:
  ansibleHost: 192.168.122.100
  node:
    networks:
    - fixedIP: 192.168.122.100
      network: ctlplane
    ansibleUser: root
    ansibleVars: |
      edpm_network_config_template: templates/net_config_bridge.j2
      edpm_network_config_hide_sensitive_logs: false
      neutron_physical_bridge_name: br-ex
      neutron_public_interface_name: eth0
      ctlplane_dns_nameservers:
      - 192.168.122.1
      dns_search_domains: []
    deploy: true
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
