---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: openstackdataplanenode-sample-inheritance-1
spec:
  node:
    ansibleHost: 192.168.122.18
    hostName: openstackdataplanenode-sample-1.localdomain
    networks:
    - fixedIP: 192.168.122.18
      network: ctlplane
  role: openstackdataplanerole-sample
