apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-0
spec:
  deployStrategy:
    deploy: true
  role: openstack-edpm-role
  hostName: edpm-compute-0
  ansibleHost: 192.168.122.100
  node:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansibleVars: |
      ctlplane_ip: 192.168.122.100
      internal_api_ip: 172.17.0.100
      storage_ip: 172.18.0.100
      tenant_ip: 172.10.0.100
      fqdn_internal_api: '{{ ansible_fqdn }}'
