apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-2
spec:
  deployStrategy:
    deploy: true
  role: openstack-edpm-role
  hostName: edpm-compute-2
  ansibleHost: 192.168.122.102
  node:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansibleVars: |
      ctlplane_ip: 192.168.122.102
      internal_api_ip: 172.17.0.102
      storage_ip: 172.18.0.102
      tenant_ip: 172.10.0.102
      fqdn_internal_api: '{{ ansible_fqdn }}'
