apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-play
  namespace: openstack
spec:
  image: "quay.io/jlarriba/openstack-tripleo-ansible-ee:stable"
  # playbook: "playbook.yaml"
  # args: ["ansible-runner", "run", "/runner", "-vvv", "-p", "test.yaml"]
  play: |
    - name: run command on all nodes
      gather_facts: false
      hosts: all
      vars:
        cmd: "uname -a"
      tasks:
        - name: run command
          shell: "{{ cmd }}"
          register: cmd_out
        - name: show command output
          debug:
            msg: "{{ cmd_out.stdout }}"
  inventory: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.1.27.21
      vars:
        ansible_ssh_user: fultonj
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  extraMounts:
    - volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key-secret
          items:
          - key: ssh_key
            path: ssh_key
      mounts:
      - name: ssh-key
        mountPath: /runner/env/ssh_key
        subPath: ssh_key
