apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./dataplane_v1beta1_openstackdataplane.yaml
namespace: openstack

        # edpm_network_config
        # Default nic config template for a EDPM compute node
        # These vars are edpm_network_config role vars
        #
        # These vars are for the network config templates themselves and are
        # considered EDPM network defaults.

        # edpm_nodes_validation




        # edpm firewall, change the allowed CIDR if needed
        # SELinux module
        # edpm_hosts_entries role
patches:
- patch: |-
    - op: replace
      path: /spec/deployStrategy/deploy
      value: true
    - op: replace
      path: /spec/roles/edpm-compute/openStackAnsibleEERunnerImage
      value: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
    - op: replace
      path: /spec/roles/edpm-compute/nodeTemplate/ansibleVars
      value: |
        service_net_map:
          nova_api_network: internal_api
          nova_libvirt_network: internal_api

        # ceph
        edpm_ceph_client_files_source: /etc/ceph
        edpm_ceph_client_files_config_home: /etc/ceph

        # edpm_network_config
        # Default nic config template for a EDPM compute node
        # These vars are edpm_network_config role vars
        edpm_network_config_template: templates/single_nic_vlans/single_nic_vlans.j2
        edpm_network_config_hide_sensitive_logs: false
        #
        # These vars are for the network config templates themselves and are
        # considered EDPM network defaults.
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0
        ctlplane_mtu: 1500
        ctlplane_subnet_cidr: 24
        ctlplane_gateway_ip: 192.168.122.1
        ctlplane_host_routes:
        - ip_netmask: 0.0.0.0/0
          next_hop: 192.168.122.1
        external_mtu: 1500
        external_vlan_id: 44
        external_cidr: '24'
        external_host_routes: []
        internal_api_mtu: 1500
        internal_api_vlan_id: 20
        internal_api_cidr: '24'
        internal_api_host_routes: []
        storage_mtu: 1500
        storage_vlan_id: 21
        storage_cidr: '24'
        storage_host_routes: []
        tenant_mtu: 1500
        tenant_vlan_id: 22
        tenant_cidr: '24'
        tenant_host_routes: []
        role_networks:
        - InternalApi
        - Storage
        - Tenant
        networks_lower:
          External: external
          InternalApi: internal_api
          Storage: storage
          Tenant: tenant

        # edpm_nodes_validation
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false

        edpm_ovn_metadata_agent_default_transport_url: TRANSPORT_URL
        edpm_ovn_metadata_agent_metadata_agent_ovn_ovn_sb_connection: SB_CONNECTION
        edpm_ovn_metadata_agent_metadata_agent_default_nova_metadata_host: 127.0.0.1
        edpm_ovn_metadata_agent_metadata_agent_default_metadata_proxy_shared_secret: 12345678
        edpm_ovn_metadata_agent_default_bind_host: 127.0.0.1
        edpm_chrony_ntp_servers:
        - clock.redhat.com

        ctlplane_dns_nameservers:
        - 192.168.122.1
        dns_search_domains: []
        edpm_ovn_dbs:
        - OVN_DBS

        registry_name: quay.io
        registry_namespace: tripleozedcentos9
        image_tag: current-tripleo
        edpm_ovn_controller_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-ovn-controller:{{ image_tag }}"
        edpm_iscsid_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-iscsid:{{ image_tag }}"
        edpm_logrotate_crond_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-cron:{{ image_tag }}"
        edpm_nova_compute_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-compute:{{ image_tag }}"
        edpm_nova_libvirt_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-libvirt:{{ image_tag }}"
        edpm_ovn_metadata_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"

        gather_facts: false
        enable_debug: false
        # edpm firewall, change the allowed CIDR if needed
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges: ['192.168.122.0/24']
        # SELinux module
        edpm_selinux_mode: enforcing
        edpm_hosts_entries_undercloud_hosts_entries: []
        # edpm_hosts_entries role
        edpm_hosts_entries_extra_hosts_entries:
        - 172.17.0.80 glance-internal.openstack.svc neutron-internal.openstack.svc cinder-internal.openstack.svc nova-internal.openstack.svc placement-internal.openstack.svc keystone-internal.openstack.svc
        - 172.17.0.85 rabbitmq.openstack.svc
        - 172.17.0.86 rabbitmq-cell1.openstack.svc
        edpm_hosts_entries_vip_hosts_entries: []
        hosts_entries: []
        hosts_entry: []
        plan: overcloud
    - op: replace
      path: /spec/roles/edpm-compute/networkAttachments
      value: [   "ctlplane",   "internalapi",   "storage",   "tenant" ]
    - op: replace
      path: /spec/roles/edpm-compute/nodeTemplate/ansibleSSHPrivateKeySecret
      value: dataplane-ansible-ssh-private-key-secret
    - op: replace
      path: /spec/nodes/edpm-compute-1/ansibleHost
      value: 192.168.122.101
    - op: replace
      path: /spec/nodes/edpm-compute-1/openStackAnsibleEERunnerImage
      value: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
    - op: replace
      path: /spec/nodes/edpm-compute-1/node/ansibleVars
      value: |
        ctlplane_ip: 192.168.122.101
        internal_api_ip: 172.17.0.101
        storage_ip: 172.18.0.101
        tenant_ip: 172.10.0.101
        fqdn_internal_api: '{{ ansible_fqdn }}'
    - op: replace
      path: /spec/nodes/edpm-compute-1/node/ansibleSSHPrivateKeySecret
      value: dataplane-ansible-ssh-private-key-secret
  target:
    kind: OpenStackDataPlane
